server:
  port: 8088

spring:
  application:
    name: sample-code-test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample_db?useSSL=false #create db scheme and add scheme name
    username: root #change db username
    password: password #change db password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

token-resource-server-config:
  token-check-uri: "https://dev.gigagates.com/qq-delivery-auth-server/oauth/check_token" #add token check url
  client-id: "QQ-Delivery" #add client id
  client-secret: "L3xLZ28FsTpOmfj6jcgi" #add client secret

logging:
  level:
    org:
      springframework:
        security: DEBUG

